"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
async function get(url){const r=await fetch(url,{headers:{accept:"text/html,application/json,text/css","user-agent":"WaterfallV15ProductionProbe/1.0"}});const text=await r.text();console.log("PROBE",JSON.stringify({url,status:r.status,type:r.headers.get("content-type"),length:text.length,head:text.slice(0,180).replace(/\s+/g," ")}));return{r,text}}
test("Waterfall v1.5 production page, hero and Miners proxy are live",async()=>{
 const page=await get("https://chrisizworski.com/national-tools/waterfalls/");assert.equal(page.r.status,200);assert.match(page.text,/Waterfall Window/);assert.match(page.text,/waterfall-hero\.css/);assert.match(page.text,/What this means/);
 const hero=await get("https://chrisizworski.com/national-tools/waterfalls/_assets/waterfall-hero.css");assert.equal(hero.r.status,200);assert.match(hero.text,/data:image\/webp;base64/);
 const css=await get("https://chrisizworski.com/national-tools/waterfalls/_assets/waterfall-page-v2.css");assert.equal(css.r.status,200);assert.match(css.text,/\.narrative/);
 const search=await get("https://chrisizworski.com/national-tools/waterfalls/_search?q=Miners%20Falls");assert.equal(search.r.status,200);const sd=JSON.parse(search.text);const item=(sd.results||[]).find(x=>/Miners Falls/i.test(x.name||""))||sd.results?.[0];assert.ok(item?.latitude&&item?.longitude);
 const api=await get(`https://chrisizworski.com/national-tools/waterfalls/_api?lat=${encodeURIComponent(item.latitude)}&lon=${encodeURIComponent(item.longitude)}&name=${encodeURIComponent(item.name)}`);assert.equal(api.r.status,200);const d=JSON.parse(api.text);console.log("MINERS_PROD",JSON.stringify({methodology:d.methodology_version,mode:d.evidence_mode,score:d.intelligence?.now?.score,label:d.intelligence?.now?.label,confidence:d.intelligence?.confidence,flow_cfs:d.intelligence?.now?.flow_cfs,regional_percentile:d.regional_proxy?.percentile,gauge_count:d.regional_proxy?.gauge_count,narrative:d.narrative}));assert.equal(d.methodology_version,"waterfall-window-v1.5.0");assert.equal(d.evidence_mode,"regional-proxy");assert.ok(Number.isFinite(d.intelligence?.now?.score));assert.equal(d.intelligence?.now?.flow_cfs,null);assert.ok(d.regional_proxy?.gauge_count>=1);assert.match(d.narrative?.summary||"",/does not assign another river's flow rate/i);
});
