"use strict";
function finite(v,min=-Infinity,max=Infinity){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,v))}
function round(v,d=0){const n=finite(v);if(n==null)return null;const p=10**d;return Math.round(n*p)/p}
function interp(points,v){const n=finite(v);if(n==null)return null;const a=[...points].sort((x,y)=>x[0]-y[0]);if(n<=a[0][0])return a[0][1];if(n>=a.at(-1)[0])return a.at(-1)[1];for(let i=1;i<a.length;i++){if(n<=a[i][0]){const[x1,y1]=a[i-1],[x2,y2]=a[i],t=(n-x1)/(x2-x1||1);return y1+t*(y2-y1)}}return a.at(-1)[1]}
function ratio(flow,s){const q=finite(flow,0),m=finite(s?.p50,0.000001);return q==null||m==null?null:q/m}
function flowScore(flow,s={}){const q=finite(flow,0),r=ratio(q,s);if(q==null||r==null)return{score:null,ratio:null,band:"unknown"};let score=interp([[.1,12],[.25,22],[.5,36],[.75,46],[1,56],[1.25,64],[1.5,72],[2,82],[3,91],[5,97],[8,100]],r);const p75=finite(s.p75,0),p90=finite(s.p90,0);if(p90!=null&&q>=p90)score+=4;else if(p75!=null&&q>=p75)score+=2;let band=r<.4?"very-low":r<.75?"low":r<1.35?"typical":r<2.25?"high":"very-high";return{score:Math.round(clamp(score)),ratio:round(r,2),band}}
function label(score){const n=finite(score,0,100);if(n==null)return"Limited evidence";if(n>=92)return"Exceptional";if(n>=80)return"Excellent";if(n>=68)return"Very good";if(n>=55)return"Good";if(n>=40)return"Fair";if(n>=25)return"Low flow";return"Very low flow"}
function confidence(i={}){let v=0;if(i.has_reach)v+=.2;if(i.has_nwm)v+=.28;if(i.has_gauge)v+=i.gauge_relation==="upstream-mainstem"?.22:.16;if(i.has_seasonal)v+=.2;if(i.has_precip)v+=.1;if(i.regulated_flow)v-=.1;v=clamp(v*100)/100;if(!i.has_gauge||!i.has_seasonal)v=Math.min(v,.55);return{value:round(v,2),label:v>=.78?"High":v>=.56?"Moderate":"Low"}}
function caution(current,s={},peak){const p90=finite(s.p90,0),r=ratio(Math.max(finite(current,0)||0,finite(peak,0)||0),s);const elevated=(p90!=null&&Math.max(current||0,peak||0)>=p90*1.75)||(r!=null&&r>=4);return elevated?{level:"elevated",message:"Very high water may make viewpoints, crossings, trails or river edges hazardous. Check local closures and warnings before visiting."}:{level:"normal",message:"The spectacle score describes water volume, not trail, access or river-edge safety. Check local conditions before visiting."}}
function pickFlow(values=[],hours=24){const now=Date.now(),end=now+hours*3600000,pts=values.map(p=>({time:p.time||p.valid_time||p.validTime||null,flow:finite(p.flow??p.value,0)})).filter(p=>p.flow!=null&&Date.parse(p.time||"")>=now-3*3600000&&Date.parse(p.time||"")<=end).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));if(!pts.length)return null;const peak=pts.reduce((x,p)=>!x||p.flow>x.flow?p:x,null);return{peak_flow:peak.flow,peak_time:peak.time,end_flow:pts.at(-1).flow,end_time:pts.at(-1).time}}
function reasons(i={}){const out=[],r=finite(i.ratio_to_seasonal_median,0);if(r!=null)out.push(r>=2.5?`Flow is about ${round(r,1)}× the seasonal median.`:r>=1.35?"Flow is running above the seasonal norm.":r<.6?"Flow is running well below the seasonal norm.":"Flow is near the usual range for this time of year.");const t=finite(i.trend_percent_24h,-1000,1000);if(t!=null)out.push(t>=15?`The connected gauge is rising (${Math.round(t)}% over about 24 hours).`:t<=-15?`The connected gauge is falling (${Math.round(Math.abs(t))}% over about 24 hours).`:"The connected gauge is roughly steady.");const future=finite(i.nwm_peak_72h_cfs,0),current=finite(i.current_flow_cfs,0);if(future!=null&&current>0){const c=future/current;if(c>=1.35)out.push("The National Water Model projects a meaningful rise within three days.");else if(c<=.75)out.push("Modeled flow is expected to ease over the next three days.")}const q=finite(i.qpf_72h_in,0);if(q!=null&&q>=.5)out.push(`${round(q,2)} in of forecast precipitation supports the future-flow outlook.`);return out.slice(0,4)}
function buildWaterfallWindow(i={}){const s=i.seasonal||{},current=finite(i.current_flow_cfs,0)??finite(i.nwm_current_cfs,0),f24=finite(i.nwm_peak_24h_cfs,0)??current,f72=finite(i.nwm_peak_72h_cfs,0)??f24;const n=flowScore(current,s),d=flowScore(f24,s),t=flowScore(f72,s),conf=confidence({has_reach:!!i.has_reach,has_nwm:!!i.has_nwm,has_gauge:!!i.has_gauge,has_seasonal:!!i.has_seasonal,has_precip:!!i.has_precip,gauge_relation:i.gauge_relation,regulated_flow:!!i.regulated_flow});let c=caution(current,s,f72);if(i.regulated_flow)c={...c,regulation:"An upstream dam or reservoir was detected. Release operations can make model-to-waterfall flow less representative than on a free-flowing stream."};return{now:{...n,label:label(n.score),flow_cfs:round(current,1)},next_24h:{...d,label:label(d.score),peak_flow_cfs:round(f24,1),peak_time:i.nwm_peak_24h_time||null},next_3d:{...t,label:label(t.score),peak_flow_cfs:round(f72,1),peak_time:i.nwm_peak_72h_time||null},confidence:conf,caution:c,reasons:reasons({ratio_to_seasonal_median:n.ratio,trend_percent_24h:i.trend_percent_24h,nwm_peak_72h_cfs:f72,current_flow_cfs:current,qpf_72h_in:i.qpf_72h_in})}}
module.exports={buildWaterfallWindow,flowScore,pickFlow,label,confidence};
